//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHCBWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boardinterface
    {
        public int boardId { get; set; }
        public int slot { get; set; }
        public string alias { get; set; }
        public int interfaceDescriptionId { get; set; }
        public string control { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> length { get; set; }
        public string color { get; set; }
        public string hide { get; set; }
        public Nullable<double> uplimit { get; set; }
        public Nullable<double> lowlimit { get; set; }
        public Nullable<double> max { get; set; }
        public Nullable<double> min { get; set; }
        public string type { get; set; }
        public Nullable<double> default_value { get; set; }
        public Nullable<double> value { get; set; }
        public string description { get; set; }
    
        public virtual board board { get; set; }
        public virtual interfaceDescription interfaceDescription { get; set; }
    }
}
