//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHCBWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ghcbDBEntities : DbContext
    {
        public ghcbDBEntities()
            : base("name=ghcbDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app> apps { get; set; }
        public virtual DbSet<appUser> appUsers { get; set; }
        public virtual DbSet<board> boards { get; set; }
        public virtual DbSet<boardinterface> boardinterfaces { get; set; }
        public virtual DbSet<interfaceDescription> interfaceDescriptions { get; set; }
        public virtual DbSet<userboard> userboards { get; set; }
    }
}
