//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GHCBWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userboard
    {
        public int userId { get; set; }
        public int boardId { get; set; }
        public string role { get; set; }
    
        public  appUser appUser { get; set; }
        public  board board { get; set; }
    }
}
